language: node_js
node_js:
  - "stable"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "4.2"

services:
  - redis-server

# run before everey other script
before_script:
  - npm install

# run some scripts
script:
  # run tests
  - npm run-script test-travis

# trigger some additional tools after success
after_success:
  # send coverage data to coveralls
  - npm run-script coveralls
  # send coverage data to codeclimate
  - npm run-script codeclimate
